version: '3.8'

services:
  web:
    image: documents_compress
    build:
      context: ./
      target: production
    volumes:
      - .:/src
    command: npm run start
    ports:
      - "4001:3000"
    environment:
      NODE_ENV: development
      DEBUG: nodejs-docker-express:*
    networks:
      - app-network

networks:
  app-network:
    external: true
    driver: bridge